#!/bin/sh

###############################################################################
##
##  3D-RISM-SCF EXAMPLE
##
###############################################################################

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "$EXAMPLE_DIR : starting"
$ECHO
$ECHO "This example shows how to use 3D-RISM-SCF to calculate"
$ECHO "1) H2O molecule in NaCl(aq), and"
$ECHO "2) HCHO molecule in water."
$ECHO
$ECHO "Also ESM-RISM is performed to calculate"
$ECHO "3) Vacuum/Li(100)/EtOH, and"
$ECHO "4) Vacuum/Al(111)/NaCl(aq,5.0M) where slab of Al is charged."
$ECHO

# set the needed environment variables
. ../../../environment_variables

# required executables, pseudopotentials and molecules
BIN_LIST="pw.x pprism.x"
PSEUDO_LIST="H.blyp-van_ak.UPF C.blyp-van_ak.UPF O.blyp-van_ak.UPF Li.pbe-n-van.UPF Al.pbe-rrkj.UPF"
MOL_LIST="H2O.spc.MOL Na+.aq.MOL Cl-.aq.MOL Ethanol.oplsua.MOL"

$ECHO
$ECHO "  executables directory: $BIN_DIR"
$ECHO "  pseudo directory:      $PSEUDO_DIR"
$ECHO "  temporary directory:   $TMP_DIR"
$ECHO "  checking that needed directories and files exist...\c"

# check for directories
for DIR in "$BIN_DIR" "$PSEUDO_DIR" ; do
    if test ! -d $DIR ; then
        $ECHO
        $ECHO "ERROR: $DIR not existent or not a directory"
        $ECHO "Aborting"
        exit 1
    fi
done
for DIR in "$TMP_DIR" "$EXAMPLE_DIR/results" ; do
    if test ! -d $DIR ; then
        mkdir $DIR
    fi
done
cd $EXAMPLE_DIR/results

# check for executables
for FILE in $BIN_LIST ; do
    if test ! -x $BIN_DIR/$FILE ; then
        $ECHO
        $ECHO "ERROR: $BIN_DIR/$FILE not existent or not executable"
        $ECHO "Aborting"
        exit 1
    fi
done

# check for pseudopotentials
for FILE in $PSEUDO_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Downloading $FILE to $PSEUDO_DIR...\c"
            $WGET $PSEUDO_DIR/$FILE $NETWORK_PSEUDO/$FILE 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# check for molecules
for FILE in $MOL_LIST ; do
    if test ! -r $PSEUDO_DIR/$FILE ; then
       $ECHO
       $ECHO "Copy $FILE to $PSEUDO_DIR...\c"
       cp $EXAMPLE_DIR/MOL/$FILE $PSEUDO_DIR 2> /dev/null
    fi
    if test $? != 0; then
        $ECHO
        $ECHO "ERROR: $PSEUDO_DIR/$FILE not existent or not readable"
        $ECHO "Aborting"
        exit 1
    fi
done
$ECHO " done"

# how to run executables
PW_COMMAND="$PARA_PREFIX $BIN_DIR/pw.x $PARA_POSTFIX"
PP_COMMAND="$PARA_PREFIX $BIN_DIR/pprism.x $PARA_POSTFIX"
$ECHO
$ECHO "  running pw.x     as: $PW_COMMAND"
$ECHO "  running pprism.x as: $PP_COMMAND"
$ECHO

# 3D-RISM-SCF calculation for H2O in NaCl(aq)
cat > H2O.NaCl_aq.in << EOF
 &control
    calculation = 'relax'
    prefix      = 'H2O.NaCl_aq'
    pseudo_dir  = '$PSEUDO_DIR/'
    outdir      = '$TMP_DIR/'
    trism       = .true.
 /
 &system
    ibrav       = 1
    a           = 10.0
    ntyp        = 2
    nat         = 3
    ecutwfc     = 25.0
    ecutrho     = 225.0
    occupations = 'fixed'
 /
 &electrons
    mixing_beta = 0.4
 /
 &ions
    ion_dynamics = 'bfgs'
 /
 &rism
    nsolv    = 3
    closure  = 'kh'
    tempv    = 300.0  ! Kelvin
    ecutsolv = 144.0  ! Rydberg
    ! Lennard-Jones for each atom (SPC model)
    solute_epsilon(1) = 0.1554  ! kcal/mol
    solute_sigma(  1) = 3.1660  ! angstrom
    solute_epsilon(2) = 0.0460
    solute_sigma(  2) = 1.0000
    ! 1D-RISM's setting
    starting1d      = 'zero'
    rism1d_conv_thr = 1.0e-8
    rism1d_maxstep  = 10000
    mdiis1d_size    = 20
    mdiis1d_step    = 0.5
    ! 3D-RISM's setting
    starting3d      = 'zero'
    rism3d_maxstep  = 2000
    rism3d_conv_thr = 1.0e-3
    mdiis3d_size    = 10
    mdiis3d_step    = 0.8
 /
ATOMIC_SPECIES
 O  -1.0  O.blyp-van_ak.UPF
 H  -1.0  H.blyp-van_ak.UPF
ATOMIC_POSITIONS {angstrom}
 O  5.00000  5.00000  5.00000  0 0 0
 H  5.81649  5.57736  5.00000
 H  4.18351  5.57736  5.00000
K_POINTS {gamma}
SOLVENTS {mol/L}
 H2O  -1.0  H2O.spc.MOL
 Na+   0.5  Na+.aq.MOL
 Cl-   0.5  Cl-.aq.MOL
EOF
$ECHO "  running the 3D-RISM-SCF calculation for H2O in NaCl(aq)...\c"
$PW_COMMAND < H2O.NaCl_aq.in > H2O.NaCl_aq.out
check_failure $?
cp -f $TMP_DIR/H2O.NaCl_aq.1drism ./
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/H2O.NaCl_aq*
$ECHO " done"

# 3D-RISM-SCF calculation for HCHO in water
cat > HCHO.aq.in << EOF
 &control
    calculation = 'scf'
    prefix      = 'HCHO.aq'
    pseudo_dir  = '$PSEUDO_DIR/'
    outdir      = '$TMP_DIR/'
    trism       = .true.
 /
 &system
    ibrav       = 1
    a           = 10.0
    ntyp        = 3
    nat         = 4
    ecutwfc     = 25.0
    ecutrho     = 225.0
    occupations = 'fixed'
 /
 &electrons
    mixing_beta = 0.4
 /
 &rism
    nsolv    = 1
    closure  = 'kh'
    tempv    = 300.0  ! Kelvin
    ecutsolv = 144.0  ! Rydberg
    ! Lennard-Jones
    solute_lj(1) = 'opls-aa'
    solute_lj(2) = 'opls-aa'
    solute_lj(3) = 'opls-aa'
 /
ATOMIC_SPECIES
 C  -1.0  C.blyp-van_ak.UPF
 O  -1.0  O.blyp-van_ak.UPF
 H  -1.0  H.blyp-van_ak.UPF
ATOMIC_POSITIONS {angstrom}
 C  5.000  5.609  5.000  0 0 0
 O  5.000  4.425  5.000
 H  4.075  6.191  5.000
 H  5.925  6.191  5.000
K_POINTS {gamma}
SOLVENTS {g/cm^3}
 H2O  1.0  H2O.spc.MOL
EOF
$ECHO "  running the 3D-RISM-SCF calculation for HCHO in water...\c"
$PW_COMMAND < HCHO.aq.in > HCHO.aq.out
check_failure $?
cp -f $TMP_DIR/HCHO.aq.1drism ./
$ECHO " done"

# plot solvent distribution
cat > HCHO.aq.post.in << EOF
 &inputpp
    prefix  = 'HCHO.aq'
    outdir  = '$TMP_DIR/'
    lpunch  = .true.
 /
 &plot
    iflag         = 3  ! 3D plot
    output_format = 6  ! Gaussian's CUBE
 /
EOF
$ECHO "  running the postprocessing to plot solvent...\c"
$PP_COMMAND < HCHO.aq.post.in > HCHO.aq.post.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/HCHO.aq*
$ECHO " done"

# ESM-RISM calculation for Li(100) with ethanol
cat > Li-EtOH.in << EOF
 &control
    calculation = 'scf'
    prefix      = 'Li-EtOH'
    pseudo_dir  = '$PSEUDO_DIR/'
    outdir      = '$TMP_DIR/'
    trism       = .true.
 /
 &system
    ibrav       = 6
    a           = 3.43
    c           = 24.0
    ntyp        = 1
    nat         = 5
    ecutwfc     = 25.0
    ecutrho     = 225.0
    occupations = 'smearing'
    smearing    = 'gauss'
    degauss     = 0.01
    ! ESM
    assume_isolated = 'esm'
    esm_bc          = 'bc1'
 /
 &electrons
    mixing_beta = 0.4
 /
 &rism
    nsolv    = 1
    closure  = 'kh'
    tempv    = 300.0  ! Kelvin
    ecutsolv = 144.0  ! Rydberg
    ! Lennard-Jones
    solute_lj(1) = 'uff'
    ! Laue-RISM
    laue_expand_right   = 50.00 ! bohr
    laue_starting_right =  3.24 ! bohr
    laue_buffer_right   =  2.00 ! bohr
 /
ATOMIC_SPECIES
Li  -1.0  Li.pbe-n-van.UPF
ATOMIC_POSITIONS {alat}
Li  0.0  0.0 -1.0
Li  0.5  0.5 -0.5
Li  0.0  0.0  0.0
Li  0.5  0.5  0.5
Li  0.0  0.0  1.0
K_POINTS {automatic}
 2 2 1 0 0 0
SOLVENTS {mol/L}
EtOH -1.0  Ethanol.oplsua.MOL
EOF
$ECHO "  running the ESM-RISM calculation for Li(100) with ethanol...\c"
$PW_COMMAND < Li-EtOH.in > Li-EtOH.out
check_failure $?
cp -f $TMP_DIR/Li-EtOH.1drism ./
cp -f $TMP_DIR/Li-EtOH.rism1 ./
cp -f $TMP_DIR/Li-EtOH.esm1 ./
$ECHO " done"

# plot solvent distribution
cat > Li-EtOH.post.in << EOF
 &inputpp
    prefix  = 'Li-EtOH'
    outdir  = '$TMP_DIR/'
    lpunch  = .true.
 /
 &plot
    iflag         = 3  ! 3D plot
    output_format = 6  ! Gaussian's CUBE
 /
EOF
$ECHO "  running the postprocessing to plot solvent...\c"
$PP_COMMAND < Li-EtOH.post.in > Li-EtOH.post.out
check_failure $?
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/Li-EtOH*
$ECHO " done"

# ESM-RISM calculation for charged Al(111) with NaCl(aq)/5.0M
cat > Al-NaCl_aq.in << EOF
 &control
    calculation   = 'relax'
    prefix        = 'Al-NaCl_aq'
    pseudo_dir    = '$PSEUDO_DIR/'
    outdir        = '$TMP_DIR/'
    trism         = .true.
    forc_conv_thr = 2.0e-3
 /
 &system
    ibrav       = 4
    a           = 2.86
    c           = 24.0
    ntyp        = 1
    nat         = 3
    ecutwfc     = 25.0
    ecutrho     = 225.0
    occupations = 'smearing'
    smearing    = 'gauss'
    degauss     = 0.01
    ! Charged
    tot_charge  = +0.1
    ! ESM
    assume_isolated = 'esm'
    esm_bc          = 'bc1'
 /
 &electrons
    mixing_beta = 0.2
 /
 &ions
    ion_dynamics = 'bfgs'
 /
 &rism
    nsolv    = 3
    closure  = 'kh'
    tempv    = 300.0  ! Kelvin
    ecutsolv = 100.0  ! Rydberg
    ! Lennard-Jones
    solute_lj(1) = 'uff'
    ! Laue-RISM
    laue_expand_right   = 50.00 ! bohr
    laue_starting_right =  0.00 ! bohr
 /
ATOMIC_SPECIES
Al  -1.0  Al.pbe-rrkj.UPF
ATOMIC_POSITIONS {angstrom}
Al  0.00  0.00 -2.00  0 0 0
Al -0.00  1.65  0.09  0 0 1
Al  1.43  0.83  2.17  0 0 1
K_POINTS {automatic}
 2 2 1 0 0 0
SOLVENTS {mol/L}
 H2O -1.0  H2O.spc.MOL
 Na+  5.0  Na+.aq.MOL
 Cl-  5.0  Cl-.aq.MOL
EOF
$ECHO "  running the ESM-RISM calculation for charged Al(111) with NaCl(aq)/5.0M...\c"
$PW_COMMAND < Al-NaCl_aq.in > Al-NaCl_aq.out
check_failure $?
cp -f $TMP_DIR/Al-NaCl_aq.1drism ./
cp -f $TMP_DIR/Al-NaCl_aq.rism1 ./
cp -f $TMP_DIR/Al-NaCl_aq.esm1 ./
$ECHO " done"

# clean TMP_DIR
$ECHO "  cleaning $TMP_DIR...\c"
rm -rf $TMP_DIR/Al-NaCl_aq*
$ECHO " done"

$ECHO
$ECHO "$EXAMPLE_DIR: done"
